#!/usr/bin/env bash

# Copyright © 2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
pass=$(SYSTEMD_COLORS=y systemd-ask-password 'Passphrase for QPDF:')
exec qpdf @<(printf -- '--password=%s' "$pass") "$@"

# vim:ts=4 sts=4 sw=4 et
